### ISSUE TITLE
Remove native dependencies

### ISSUE THREAD

**Issue by feross** [guerrerocarlos/node-airplay-js#8]
The goal of this module is to be pure JavaScript, correct? The dependency `asyncblock` requires a compiled, native dependency `fibers`. Can we eliminate this dependency so `airplay-js` is pure-JS again?

**Comment by xat** [comment]
+1
This is also making trouble down-the-line ( see https://github.com/xat/castnow/issues/75 )
Would be awesome if that unused dependency could get removed.

**Comment by feross** [comment]
Here's a PR to fix the issue: https://github.com/guerrerocarlos/node-airplay-js/pull/9

**Comment by xat** [comment]
thanks :)
